Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;

namespace MPP.Controllers
{
    public class ImportController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        public ImportController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Import()
        {
            return View("Index");
        }
        [HttpPost]
        public ActionResult OnPostImport()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName);
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook   
                    }
                    IRow headerRow = sheet.GetRow(0); //Get Header Row
                    int cellCount = headerRow.LastCellNum;
                    sb.Append("<table class='table'><tr>");
                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
                        sb.Append("<th>" + cell.ToString() + "</th>");
                    }
                    sb.Append("</tr>");
                    sb.AppendLine("<tr>");
                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;
                        for (int j = row.FirstCellNum; j < cellCount; j++)
                        {
                            if (row.GetCell(j) != null)
                                sb.Append("<td>" + row.GetCell(j).ToString() + "</td>");
                        }
                        sb.AppendLine("</tr>");
                    }
                    sb.Append("</table>");
                }
            }
            return this.Content(sb.ToString());
        }
    }
}

Views/Import/Index.cshtml
<!--SHOW RISK IN THE FORM OF TABLE FOR SPECIFIC PROJECT-->
@model IEnumerable<ASP.NET_CORE_MVC_EMP_MGMT.Models.Risk>
@using ASP.NET_CORE_MVC_EMP_MGMT.Models
<head>
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    <!-- create two column of the page-->
    <div class="row">
        <div class="left-page" style="margin-top:60px;">
            <h3 style="font-family:Helvetica, Arial, sans-serif ;color:white; text-align:center;">Menu</h3>
            <hr style="border-width: 6px;color:white;" />
            <button type="button" class="collapsible" style="font-size:17px;">Projects  <i class="fas fa-angle-right"></i></button>
            <div class="content">
                <ul style="text-align:center;">
                    <a style="color:white;" asp-controller="Risk" asp-action="RiskTable">Project Control Register</a>
                    <br />
                    <a style="color:white;" href="#">OFAG</a>
                    <br />
                    <a style="color:white;" href="#">MINT</a>
                    <br />
                    <a style="color:white;" href="#">PCR</a>
                    <br />
                    <a style="color:white;" href="#">PCR</a>
                    <br />
                </ul>
            </div>
            <div>
                <a asp-controller="Project" asp-action="CreateNewProject"><button type="button" class="collapsible" style="font-size:17px;">Create Project <i class="fas fa-plus"></i></button></a>
            </div>
            <div>
                <a asp-controller="Project" asp-action="ProjectSummary"><button type="button" class="collapsible" style="font-size:17px;">Project Summary</button></a>
            </div>
        </div><!--end left page-->
        <div class="right-page" style="background-color:white; margin-top:60px;">
            <h6 style="margin-left:60%;">You are at: <a asp-controller="home" asp-action="index">Projects >>  </a><a asp-controller="Project" asp-action="ProjectSummary">@ViewBag.ProjectName >></a> <a href="#">Schedule</a></h6>
            <hr />
            <div class="right-row">
                <div class="pill-nav">
                    <a class="active" asp-controller="Import" asp-action="Import">Schedule</a>
                    <a asp-controller="Risk" asp-action="RiskTable">Risk Log</a>
                    <a asp-controller="Issue" asp-action="IssueTable">Issue Log</a>
                    <a asp-controller="Actiono" asp-action="ActionoTable">Action Log</a>
                    <a asp-controller="Home" asp-action="report">Report</a>
                </div>
                <hr />
                <form method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="file" id="fUpload" name="files" class="form-control" />
                        </div>
                        <div class="col-md-8">
                            <input type="button" id="btnUpload" value="Upload" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8" style="padding-top:10px;">
                            <button asp-page-handler="Export">Export</button>
                        </div>
                    </div>
                    <br />
                    <div id="dvData"></div>
                </form>


            </div>
            <hr />

            

        </div>
    </div><!-- end div .row-->

</body>



<script src="~/js/jquery-1.10.2.min.js"></script>
<script src="~/js/JavaScript.js"></script>
<script src="~/js/site.js"></script>

<script>
    $(document).ready(function () {
        $('#btnUpload').on('click', function () {
            var fileExtension = ['xls', 'xlsx'];
            var filename = $('#fUpload').val();
            if (filename.length == 0) {
                alert("Please select a file.");
                return false;
            }
            else {
                var extension = filename.replace(/^.*\./, '');
                if ($.inArray(extension, fileExtension) == -1) {
                    alert("Please select only excel files.");
                    return false;
                }
            }
            var fdata = new FormData();
            var fileUpload = $("#fUpload").get(0);
            var files = fileUpload.files;
            fdata.append(files[0].name, files[0]);
            $.ajax({
                type: "POST",
                url: "/Import/OnPostImport",
                //url: "/Import?handler=OnPostImport",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-TOKEN",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                data: fdata,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.length == 0)
                        alert('Some error occured while uploading');
                    else {
                        $('#dvData').html(response);
                    }
                },
                error: function (e) {
                    $('#dvData').html(e.responseText);
                }
            });
        })
    });
</script>