Models/Risk.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_CORE_MVC_EMP_MGMT.Models
{
    public class Risk
    {
        [Key]
        public int RiskCode { get; set; }
        [Required]
        [Display(Name = "Risk Description: ")]
        public String RiskDescription { get; set; }// the second column in Employees table
        [Required]
        [Display(Name = "Risk Owner: ")]
        public String RiskOwner { get; set; }
        [Required]
        [Display(Name = "Risk Open Date: ")]
        [DataType(DataType.Date)]
        public DateTime RiskOpenDate { get; set; }
        [Required]
        [Display(Name = "Risk Close Date: ")]
        [DataType(DataType.Date)]
        public DateTime RiskCloseDate { get; set; }
        [Required]
        [Display(Name = "Risk Status: ")]
        public ClosedOpened RiskStatus { get; set; }
        [Required]
        [Display(Name = "Risk Impact: ")]
        public LowMediumHigh RiskImpact { get; set; }
        [Required]
        [Display(Name = "Agreed Solution: ")]
        public String RiskAgreedSolution { get; set; }

        //foreign key
        public int? ProjectProjectCode { get; set; }
        [ForeignKey("ProjectProjectCode")]
        public virtual Project Project { get; set; }
        
    }
}

Controllers/RiskController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_CORE_MVC_EMP_MGMT.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASP.NET_CORE_MVC_EMP_MGMT.Controllers
{
    public class RiskController : Controller
    {
        
        private readonly AppDbContext _context;
        private readonly IRisk _iRisk;
        private static int code;//store  ProjectCode passed from ProjectSummary.cshtml
        private static string ProjectName;
        public RiskController(AppDbContext context, IRisk iRisk)
        {
            _context = context;
            _iRisk = iRisk;
            
        }
        
        //method to display all risks of a project in table format
        public IActionResult RiskTable(int id)//id is ProjectCode passed from ProjectSummary.cshtml
        {
            var Username = HttpContext.Session.GetString("Username");

            if (Username != null)
            {
                code = id;//set the Global variable 'code'
                ViewBag.Code = code;
                var model = _iRisk.GetAllProjectRisk(id);//interface in IRisk to display all risks for this projectcode
                ViewBag.Risk = model;
                //get the name of the project based on the id and pass it to RiskTable.cshtml to use it
                //to indicate where the user is at
                ProjectName = _context
                .Projects
                .Where(u => u.ProjectCode == id)
                .Select(u => u.projectName)
                .SingleOrDefault();
                ViewBag.ProjectName = ProjectName;

                //pass the global code value to IssueTable.cshtml
                ViewBag.ProjectCode = code;
                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }


        }
        
        [HttpPost]
        public IActionResult RiskTable(int id, string search = null)
        {
            id = code;
            if (!string.IsNullOrEmpty(search))
            {
                var foundRisks = _iRisk.SearchRisk(search);
                return View(foundRisks);
            }
            var allRisk = _iRisk.GetAllProjectRisk(id);
            ViewBag.Project = allRisk;

            //pass the global code value to IssueTable.cshtml
            ViewBag.ProjectCode = code;
            return View(allRisk);
        }
        
        // GenerateReport i.e the whole project log file(risk,issue and action log)
        public IActionResult GenerateReport()
        {
            //var data = _context.Risks.ToList();
            var data = _context.Risks.Where(ri=>ri.ProjectProjectCode == code).ToList();
            var data2 = _context.Issues.Where(ri=>ri.ProjectProjectCode == code).ToList();
            var data3 = _context.Actionos.Where(ri => ri.ProjectProjectCode == code).ToList();

            var stream = new MemoryStream();
            using(var package = new ExcelPackage(stream))
            {
                var sheet = package.Workbook.Worksheets.Add("Risk Log");
                var sheet2 = package.Workbook.Worksheets.Add("Issue Log");
                var sheet3 = package.Workbook.Worksheets.Add("Action Log");
                sheet.Cells.LoadFromCollection(data, true);
                sheet2.Cells.LoadFromCollection(data2, true);
                sheet3.Cells.LoadFromCollection(data3, true);
                package.Save();
            }
            stream.Position = 0;
            var fileName = ProjectName+$" Log File_{DateTime.Now.ToString("yyyy/MM/dd/HH:mm:ss")}.xlsx";
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);

        }
        // Export RiskTable to file
        public IActionResult ExportRisk()
        {
            //var data = _context.Risks.ToList();
            var data = _context.Risks.Where(ri => ri.ProjectProjectCode == code).ToList();
            
            var stream = new MemoryStream();
            using (var package = new ExcelPackage(stream))
            {
                var sheet = package.Workbook.Worksheets.Add("Risk Log");
                sheet.Cells.LoadFromCollection(data, true);
                package.Save();
            }
            stream.Position = 0;
            var fileName = ProjectName + $" Risk Log_{DateTime.Now.ToString("yyyy/MM/dd/HH:mm:ss")}.xlsx";
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);

        }
        
        //when we want to edit a risk this Get method display a form with predefined values in its form
        [HttpGet]
        public ViewResult EditProjectRisk(int Id)//Id is the RiskCode of the risk we are editing passed from RiskTable.cshtml
        {
            Risk risk = _iRisk.GetRisk(Id);
            EditUpdateRisk editUpdateRisk = new EditUpdateRisk
            {
                Id = risk.RiskCode,
                RiskAgreedSolution = risk.RiskAgreedSolution,
                RiskCloseDate = risk.RiskCloseDate,
                RiskImpact = risk.RiskImpact,
                RiskOpenDate = risk.RiskOpenDate,
                RiskOwner = risk.RiskOwner,
                RiskStatus = risk.RiskStatus,
                RiskCode = risk.RiskCode,
                RiskDescription = risk.RiskDescription

            };
            ViewBag.ProjectCode = code;
            return View(editUpdateRisk);
        }
        //EditProjectRisk(); is used to add new Risk to Risk Table so this method Post the form data to database
        [HttpPost]
        public IActionResult EditProjectRisk(EditUpdateRisk model)
        {
            if (ModelState.IsValid)
            {
                Risk risk = _iRisk.GetRisk(model.Id);
                risk.RiskDescription = model.RiskDescription;
                risk.RiskImpact = model.RiskImpact;
                risk.RiskOwner = model.RiskOwner;
                risk.RiskStatus = model.RiskStatus;
                risk.RiskOpenDate = model.RiskOpenDate;
                risk.RiskCloseDate = model.RiskCloseDate;
                risk.RiskAgreedSolution = model.RiskAgreedSolution;

                _iRisk.Update(risk);//Update method is found in IRiskRepository.cs
                return RedirectToAction("RiskTable", new { id = code });
            }
            return View();
        }
        //method to delete a project risk no view is required to delete a risk so this method work on get method
        public async Task<IActionResult> DeleteProjectRisk(int id)
        {
            var risk = await _context.Risks.FindAsync(id);
            _context.Risks.Remove(risk);

            await _context.SaveChangesAsync();
            
            return RedirectToAction("RiskTable", new { id = code });
        }
        
        //embi(); is used to add new Risk to Risk Table so this method Get us the form
        [HttpGet]
        public IActionResult embi()
        {
            return View();
        }

        //embi(); is used to add new Risk to Risk Table so this method Post the form data to database
        [HttpPost]
        public async Task<IActionResult> embi(Risk risk)
        {
            
            if (ModelState.IsValid)
            {
                
                Risk ri = new Risk();
                ri.RiskDescription = risk.RiskDescription;
                ri.RiskImpact = risk.RiskImpact;
                ri.RiskOwner = risk.RiskOwner;
                ri.RiskOpenDate = risk.RiskOpenDate;
                ri.RiskCloseDate = risk.RiskCloseDate;
                ri.RiskStatus = risk.RiskStatus;
                ri.RiskAgreedSolution = risk.RiskAgreedSolution;
                ri.ProjectProjectCode = code;
                
                _context.Risks.Add(ri);
                await _context.SaveChangesAsync();
                return RedirectToAction("RiskTable", new { id = code });
            }
            return View(risk);
        }

        

    }
}

Views/Risk/EditProjectRisk.cshtml
@model EditUpdateRisk
@{
    ViewData["Title"] = "Editing Project Risk";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%;margin-top:80px;">
        <form asp-controller="Risk" asp-action="EditProjectRisk" method="post">
            <!--this input field store the id of the risk which we are updating-->
            <input hidden asp-for="RiskCode" />
            
            <h3 style="color:#003cff;">Editing Project Risk</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="RiskDescription"></label>
                    <input asp-for="RiskDescription" class="form-control" name="RiskDescription" />
                    <span asp-validation-for="RiskDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RiskOwner"></label>
                    <input asp-for="RiskOwner" class="form-control" name="RiskOwner" />
                    <span asp-validation-for="RiskOwner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RiskOpenDate"></label>
                    <input asp-for="RiskOpenDate" class="form-control" />
                    <span asp-validation-for="RiskOpenDate" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="RiskImpact"></label>
                    <input asp-for="RiskImpact" class="form-control" />
                    <span asp-validation-for="RiskImpact" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="RiskImpact"></label>
                    <div>
                        <select asp-for="RiskImpact" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<LowMediumHigh>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="RiskImpact" class="text-danger"></span>
                </div>
            </div>
            <div class="leftright" style="padding-left:5%; padding-right:5%;">
                <div class="form-group">
                    <label asp-for="RiskCloseDate"></label>
                    <input asp-for="RiskCloseDate" class="form-control" />
                    <span asp-validation-for="RiskCloseDate" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="RiskStatus"></label>
                    <input asp-for="RiskStatus" class="form-control" />
                    <span asp-validation-for="RiskStatus" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="RiskStatus"></label>
                    <div>
                        <select asp-for="RiskStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="RiskStatus" class="text-danger"></span>
                </div>
                <div class="form-group" style="padding-bottom:8%;">
                    <label asp-for="RiskAgreedSolution"></label>
                    <input asp-for="RiskAgreedSolution" class="form-control" />
                    <span asp-validation-for="RiskAgreedSolution" class="text-danger"></span>
                </div>


                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-spinner fa-spin "></i> Update</button>
                    </div>
                    <div class="form-group col-md-6">
                        <a asp-controller="Risk" asp-action="RiskTable" asp-route-id="@ViewBag.ProjectCode" class="btn btn-secondary btn-block"><i class=" fa fa-table"></i> Back To Table</a>
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>

Views/Risk/RiskTable.cshtml
<!--SHOW RISK IN THE FORM OF TABLE FOR SPECIFIC PROJECT-->
@model IEnumerable<ASP.NET_CORE_MVC_EMP_MGMT.Models.Risk>
@using ASP.NET_CORE_MVC_EMP_MGMT.Models
<head>
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    <!-- create two column of the page-->
    <div class="row">
        <div class="left-page" style="margin-top:60px;">
            <h3 style="font-family:Helvetica, Arial, sans-serif ;color:white; text-align:center;">Menu</h3>
            <hr style="border-width: 6px;color:white;" />
            <div>
                <a asp-controller="Home" asp-action="Index">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-home" style="padding-right:12px;"></i>
                        Home
                    </button>
                </a>
            </div>
            
            <div>
                <a asp-controller="Project" asp-action="CreateNewProject">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-folder-plus" style="padding-right:12px;"></i>Create Project
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Project" asp-action="ProjectSummary">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fa fa-file-signature" style="padding-right:12px;">  </i>Project Summary
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Risk" asp-action="GenerateReport">
                    <button type="button" class="collapsible btn btn-primary" style="font-size:17px;">
                        <i class="fa fa-file-download" style="padding-right:12px;">  </i>  Generate Report
                    </button>
                </a>

            </div>
        </div><!--end left page-->
        <div class="right-page" style="background-color:white; margin-top:60px;">
            <h6 style="margin-left:60%;">
                You are at: <a asp-controller="home" asp-action="index">
                    Projects >>
                </a><a asp-controller="Project" asp-action="ProjectSummary">
                    @ViewBag.ProjectName >>
                </a> <a href="#">Risk Log</a>
            </h6>
            <hr />
            <div class="row">
                <div class="pill-nav" style="width:75%;margin-left:1%;">
                    <a asp-controller="Schedule" asp-action="ScheduleTable" asp-route-id="@ViewBag.ProjectCode">Schedule</a>
                    <a class="active" asp-controller="Risk" asp-action="RiskTable">Risk Log</a>
                    <a asp-controller="Issue" asp-action="IssueTable" asp-route-id="@ViewBag.ProjectCode">Issue Log</a>
                    <a asp-controller="Actiono" asp-action="ActionoTable" asp-route-id="@ViewBag.ProjectCode">Action Log</a>

                </div>
                <div>
                    <form asp-action="RiskTable" asp-controller="Risk" method="post" style="width:100%; padding:0px;">
                        <div class="row input-group">
                            <input type="text" name="search" id="search" class="form-control" placeholder="Search risk" />
                            <div>
                                <input type="submit" value="Search" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr />
            <div class="right-row">
                <table border="1" style="width:100%">
                    <thead style="background-color:darkorange;">
                        <tr>
                            <th>Code</th>
                            <th>Description</th>
                            <th>Owner</th>
                            <th>Open Date</th>
                            <th>Close Date</th>
                            <th>Status</th>
                            <th>Impact</th>
                            <th>Solution</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var risk in Model)
                        {
                            <tr>
                                <td>@risk.RiskCode</td>
                                <td>@risk.RiskDescription</td>
                                <td>@risk.RiskOwner</td>
                                <td>@risk.RiskOpenDate</td>
                                <td>@risk.RiskCloseDate</td>
                                <td>@risk.RiskStatus</td>
                                <td>@risk.RiskImpact</td>
                                <td>@risk.RiskAgreedSolution</td>
                                <td>
                                    <a asp-controller="Risk" asp-action="EditProjectRisk" asp-route-id="@risk.RiskCode">
                                        <i class="fa fa-marker"></i>
                                    </a>
                                    <a asp-controller="Risk" asp-action="DeleteProjectRisk" style="margin-left:15px;"
                                       asp-route-id="@risk.RiskCode" class="text-danger"
                                       onclick="return confirm('Are you sure to delete this risk?')">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                    


                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>



            <hr />
            <div class="row" style="margin-top:80px;">
                <div style="width:50%;">
                    <a asp-controller="Risk" asp-action="ExportRisk">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:15%;"
                                title="Download this table">
                            Download <i class="fa fa-file-download"></i>
                        </button>
                    </a>
                </div>
                <div style="width:50%;">
                    <a asp-controller="Risk" asp-action="embi">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:50%;">
                            Add Risk <i class="fa fa-plus"></i>
                        </button>
                    </a>
                </div>
               
            </div>
            @*<div class="row">
                <div style="width:50%;">
                    <a href="https://launchpad.37signals.com/authorization/new?type=web_server&client_id=0f8b523480cadae39c3941362721d775803a8ebf-id&redirect_uri=https://localhost:44369-uri">
                        basecamp
                    </a>
                </div>
                <div style="width:50%;">
                    <a asp-controller="BasecampConnection" asp-action="Basecamp"> and this from base camp
                    </a>
                </div>
            </div>*@
        </div>
    </div><!-- end div .row-->
    <!--POPUP WINDOW WHEN EDIT BUTTON OF EACH RISK IS CLICKED-->


</body>

Views/Risk/embi.cshtml
@model Risk
@{
    ViewData["Title"] = "Adding Project Risk";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%; margin-top:80px;">
        <form asp-controller="RiskController" asp-action="embi" method="post">
            <br />
            <h3 style="color:#003cff;">Adding Project Risk</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="RiskDescription"></label>
                    <input asp-for="RiskDescription" class="form-control" />
                    <span asp-validation-for="RiskDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RiskOwner"></label>
                    <input asp-for="RiskOwner" class="form-control" />
                    <span asp-validation-for="RiskOwner" class="text-danger"></span>
                </div>
                @*<div class="form-group">
            <label asp-for="RiskStatus"></label>
            <input asp-for="RiskStatus" class="form-control" />
            <span asp-validation-for="RiskStatus" class="text-danger"></span>
        </div>*@
                <div class="form-group">
                    <label asp-for="RiskStatus"></label>
                    <div>
                        <select asp-for="RiskStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="RiskStatus" class="text-danger"></span>
                </div>

                @*<div class="form-group">
                    <label asp-for="RiskImpact"></label>
                    <input asp-for="RiskImpact" class="form-control" />
                    <span asp-validation-for="RiskImpact" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="RiskImpact"></label>
                    <div>
                        <select asp-for="RiskImpact" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<LowMediumHigh>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="RiskImpact" class="text-danger"></span>
                </div>
            </div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="RiskOpenDate"></label>
                    <input asp-for="RiskOpenDate" class="form-control" />
                    <span asp-validation-for="RiskOpenDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RiskCloseDate"></label>
                    <input asp-for="RiskCloseDate" class="form-control" />
                    <span asp-validation-for="RiskCloseDate" class="text-danger"></span>
                </div>

                <div class="form-group" style="padding-bottom:8%;">
                    <label asp-for="RiskAgreedSolution"></label>
                    <input asp-for="RiskAgreedSolution" class="form-control" />
                    <span asp-validation-for="RiskAgreedSolution" class="text-danger"></span>
                </div>


                <div class="row" style="margin-left:1%;">
                    <div style=" width:30%;">
                        <button asp-controller="Risk" asp-action="RiskTable" asp-route-id="@ViewBag.ProjectCode"
                                class="btn btn-danger btn-block">
                            Cancel
                        </button>
                    </div>
                    <div style="margin-left:36%; width:30%;">
                        <input type="submit" class="btn btn-primary btn-block" value="Add Risk" />
                    </div>

                </div>

            </div>
        </form>
    </div>

</div>