Models/Issue.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_CORE_MVC_EMP_MGMT.Models
{
    public class Issue
    {
        [Key]
        public int IssueCode { get; set; }
        [Required]
        [Display(Name = "Issue Description: ")]
        public String IssueDescription { get; set; }// the second column in Employees table
        [Required]
        [Display(Name = "Issue Owner: ")]
        public String IssueOwner { get; set; }
        [Required]
        [Display(Name = "Issue Open Date: ")]
        [DataType(DataType.Date)]
        public DateTime IssueOpenDate { get; set; }
        [Required]
        [Display(Name = "Issue Close Date: ")]
        [DataType(DataType.Date)]
        public DateTime IssueCloseDate { get; set; }
        [Required]
        [Display(Name = "Issue Status: ")]
        public ClosedOpened IssueStatus { get; set; }
        
        [Display(Name = "Issue Impact: ")]
        [Required]
        public LowMediumHigh IssueImpact { get; set; }
        [Required]
        [Display(Name = "Agreed Solution: ")]
        public String IssueAgreedSolution { get; set; }

        //foreign key
        public int? ProjectProjectCode { get; set; }
        [ForeignKey("ProjectProjectCode")]
        public virtual Project Project { get; set; }
    }
}

Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_CORE_MVC_EMP_MGMT.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASP.NET_CORE_MVC_EMP_MGMT.Controllers
{
    public class IssueController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IIssueRepository _iIssueRepository;
        private static string ProjectName;
        private static int code;//store  ProjectCode passed from ProjectSummary.cshtml
        public IssueController(AppDbContext context, IIssueRepository iIssueRepository)
        {
            _context = context;
            _iIssueRepository = iIssueRepository;
        }
        //when we want to edit an issue this method respond to get method to display a form which has predefined values
        //from the database the specific issue we are editing
        [HttpGet]
        public ViewResult EditProjectIssue(int Id)//Id is the IssueCode
        {
            Issue issue = _iIssueRepository.GetIssue(Id);
            EditUpdateIssue editUpdateIssue = new EditUpdateIssue
            {
                Id = issue.IssueCode,
                IssueDescription = issue.IssueDescription,
                IssueImpact = issue.IssueImpact,
                IssueOpenDate = issue.IssueOpenDate,
                IssueCloseDate = issue.IssueCloseDate,
                IssueOwner = issue.IssueOwner,
                IssueStatus = issue.IssueStatus,
                IssueAgreedSolution = issue.IssueAgreedSolution,
                IssueCode = issue.IssueCode
            };
            ViewBag.ProjectCode = code;
            return View(editUpdateIssue);
        }
        //EditProjectIssue(); is used to add new Issue to Issue Table so this method Post the form data to database
        [HttpPost]
        public IActionResult EditProjectIssue(EditUpdateIssue model)
        {
            if (ModelState.IsValid)
            {

                Issue issue = _iIssueRepository.GetIssue(model.Id);
                issue.IssueDescription = model.IssueDescription;
                issue.IssueOwner = model.IssueOwner;
                issue.IssueImpact = model.IssueImpact;
                issue.IssueOpenDate = model.IssueOpenDate;
                issue.IssueCloseDate = model.IssueCloseDate;
                issue.IssueStatus = model.IssueStatus;
                issue.IssueAgreedSolution = model.IssueAgreedSolution;

                _iIssueRepository.Update(issue);//Update method is found in IIssueRepository.cs
                //return RedirectToAction("IssueTable");
                return RedirectToAction("IssueTable", new { id = code });
            }
            return View();
        }


        //method to delete a project Issue no view is required to delete an issue so this method work on get method
        public async Task<IActionResult> DeleteProjectIssue(int id)
        {
            var issue = await _context.Issues.FindAsync(id);
            _context.Issues.Remove(issue);
            await _context.SaveChangesAsync();
            //return RedirectToAction("IssueTable");
            return RedirectToAction("IssueTable", new { id = code });
        }

        //method to display all Issue of a project in table format
        public IActionResult IssueTable(int id)//id is ProjectCode passed from RiskTable.cshtml
        {
            var Username = HttpContext.Session.GetString("Username");

            if (Username != null)
            {
                code = id;
                ViewBag.Code = code;
                var model = _iIssueRepository.GetAllProjectIssue(id);//interface in IIssueRepository
                ViewBag.Issue = model;
                //get the name of the project based on the id and pass it to IssueTable.cshtml to use it
                //to indicate where the user is at
                ProjectName = _context
                .Projects
                .Where(u => u.ProjectCode == id)
                .Select(u => u.projectName)
                .SingleOrDefault();
                ViewBag.ProjectName = ProjectName;
                //pass the global code value to IssueTable.cshtml
                ViewBag.ProjectCode = code;
                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            
        }
        [HttpPost]
        public IActionResult IssueTable(int id, string search = null)
        {
            id = code;
            if (!string.IsNullOrEmpty(search))
            {
                var foundIssues = _iIssueRepository.SearchIssue(search);
                return View(foundIssues);
            }
            var allIssue = _iIssueRepository.GetAllProjectIssue(id);
            ViewBag.Project = allIssue;

            //pass the global code value to IssueTable.cshtml
            ViewBag.ProjectCode = code;
            return View(allIssue);
        }
        //AddIssue(); is used to add new Issue to Issue Table
        [HttpGet]
        public IActionResult AddIssue()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddIssue(Issue issue)
        {
            if (ModelState.IsValid)
            {

                Issue iss = new Issue();
                iss.IssueDescription = issue.IssueDescription;
                iss.IssueImpact = issue.IssueImpact;
                iss.IssueOwner = issue.IssueOwner;
                iss.IssueOpenDate = issue.IssueOpenDate;
                iss.IssueCloseDate = issue.IssueCloseDate;
                iss.IssueStatus = issue.IssueStatus;
                iss.IssueAgreedSolution = issue.IssueAgreedSolution;
                iss.ProjectProjectCode = code;

                _context.Issues.Add(iss);
                await _context.SaveChangesAsync();
                return RedirectToAction("IssueTable", new { id = code });
            }
            return View(issue);
        }
        // Export IssueTable 
        public IActionResult ExportIssue()
        {
            //var data = _context.Risks.ToList();
            var data = _context.Issues.Where(ri => ri.ProjectProjectCode == code).ToList();
            var stream = new MemoryStream();
            using (var package = new ExcelPackage(stream))
            {
                var sheet = package.Workbook.Worksheets.Add("Issue Log");
                sheet.Cells.LoadFromCollection(data, true);
                package.Save();
            }
            stream.Position = 0;
            var fileName = ProjectName + $" Issue Log_{DateTime.Now.ToString("yyyy/MM/dd/HH:mm:ss")}.xlsx";
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);

        }

    }
}

Views/Issue/AddIssue.cshtml
@model Issue
@{
    ViewData["Title"] = "Adding Project Issue";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%; margin-top:80px;">
        <form asp-controller="IssueController" asp-action="AddIssue" method="post">
            <br />
            <h3 style="color:#003cff;">Adding Project Issue</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="IssueDescription"></label>
                    <input asp-for="IssueDescription" class="form-control" />
                    <span asp-validation-for="IssueDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueOwner"></label>
                    <input asp-for="IssueOwner" class="form-control" />
                    <span asp-validation-for="IssueOwner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueOpenDate"></label>
                    <input asp-for="IssueOpenDate" class="form-control" />
                    <span asp-validation-for="IssueOpenDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueCloseDate"></label>
                    <input asp-for="IssueCloseDate" class="form-control" />
                    <span asp-validation-for="IssueCloseDate" class="text-danger"></span>
                </div>
            </div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                @*<div class="form-group">
            <label asp-for="IssueImpact"></label>
            <input asp-for="IssueImpact" class="form-control" />
            <span asp-validation-for="IssueImpact" class="text-danger"></span>
        </div>*@
                <div class="form-group">
                    <label asp-for="IssueImpact"></label>
                    <div>
                        <select asp-for="IssueImpact" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<LowMediumHigh>()">
                            <option value="" selected disabled>Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="IssueImpact" class="text-danger"></span>
                </div>

                @*<div class="form-group">
                    <label asp-for="IssueStatus"></label>
                    <input asp-for="IssueStatus" class="form-control" />
                    <span asp-validation-for="IssueStatus" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="IssueStatus"></label>
                    <div>
                        <select asp-for="IssueStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="IssueStatus" class="text-danger"></span>
                </div>
                <div class="form-group" style="padding-bottom:8%;">
                    <label asp-for="IssueAgreedSolution"></label>
                    <input asp-for="IssueAgreedSolution" class="form-control" />
                    <span asp-validation-for="IssueAgreedSolution" class="text-danger"></span>
                </div>
                <div class="row" style="margin-left:1%;">
                    <div style=" width:30%;">
                        <button asp-controller="Issue" asp-action="IssueTable" asp-route-id="@ViewBag.ProjectCode"
                                class="btn btn-danger btn-block">
                            Cancel
                        </button>
                    </div>
                    <div style="margin-left:36%; width:30%;">
                        <input type="submit" class="btn btn-primary btn-block" value="Add Action" />
                    </div>

                </div>

            </div>
        </form>
    </div>

</div>

Views/Issue/EditProjectIssue.cshtml
@model EditUpdateIssue
@{
    ViewData["Title"] = "Editing Project Issue";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%; margin-top:80px;">
        <form asp-controller="Risk" asp-action="EditProjectIssue" method="post">
            <!--this input field store the id of the risk which we are updating-->
            <input hidden asp-for="IssueCode" />
            <br />
            <h3 style="color:#003cff;">Editing Project Issue</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="IssueDescription"></label>
                    <input asp-for="IssueDescription" class="form-control" />
                    <span asp-validation-for="IssueDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueOwner"></label>
                    <input asp-for="IssueOwner" class="form-control" />
                    <span asp-validation-for="IssueOwner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueOpenDate"></label>
                    <input asp-for="IssueOpenDate" class="form-control" />
                    <span asp-validation-for="IssueOpenDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IssueCloseDate"></label>
                    <input asp-for="IssueCloseDate" class="form-control" />
                    <span asp-validation-for="IssueCloseDate" class="text-danger"></span>
                </div>
                

                
            </div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                @*<div class="form-group">
                    <label asp-for="IssueStatus"></label>
                    <input asp-for="IssueStatus" class="form-control" />
                    <span asp-validation-for="IssueStatus" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="IssueStatus"></label>
                    <div>
                        <select asp-for="IssueStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="IssueStatus" class="text-danger"></span>
                </div>
                @*<div class="form-group">
            <label asp-for="IssueImpact"></label>
            <input asp-for="IssueImpact" class="form-control" />
            <span asp-validation-for="IssueImpact" class="text-danger"> </span>
        </div>*@
                <div class="form-group">
                    <label asp-for="IssueImpact"></label>
                    <div>
                        <select asp-for="IssueImpact" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<LowMediumHigh>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="IssueImpact" class="text-danger"></span>
                </div>
                <div class="form-group" style="padding-bottom:8%;">
                    <label asp-for="IssueAgreedSolution"></label>
                    <input asp-for="IssueAgreedSolution" class="form-control" />
                    <span asp-validation-for="IssueAgreedSolution" class="text-danger"></span>
                </div>


                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-spinner fa-spin"></i> Update</button>
                    </div>
                    <div class="form-group col-md-6">
                        <a asp-controller="Issue" asp-action="IssueTable" asp-route-id="@ViewBag.ProjectCode" class="btn btn-secondary btn-block"><i class=" fa fa-table"></i> Back To Table</a>
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>

Views/Issue/IssueTable.cshtml
<!--SHOW RISK IN THE FORM OF TABLE FOR SPECIFIC PROJECT-->
@model IEnumerable<ASP.NET_CORE_MVC_EMP_MGMT.Models.Issue>
<head>
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    <!-- create two column of the page-->
    <div class="row">
        <div class="left-page" style="margin-top:60px;">
            <h3 style="font-family:Helvetica, Arial, sans-serif ;color:white; text-align:center;">Menu</h3>
            <hr style="border-width: 6px;color:white;" />
            <div>
                <a asp-controller="Home" asp-action="Index">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-home" style="padding-right:12px;"></i>
                        Home
                    </button>
                </a>
            </div>
            
            <div>
                <a asp-controller="Project" asp-action="CreateNewProject">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-folder-plus" style="padding-right:12px;"></i>Create Project
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Project" asp-action="ProjectSummary">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fa fa-file-signature" style="padding-right:12px;">  </i>Project Summary
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Risk" asp-action="GenerateReport">
                    <button type="button" class="btn btn-outline-success" style="font-size:17px; color:white;">
                        <i class="fa fa-file-download" style="padding-right:12px;">  </i>  Generate Report
                    </button>
                </a>

            </div>
        </div><!--end left page-->
        <div class="right-page" style="background-color:white;">
            
            <h6 style="margin-left:60%;">
                You are at: <a asp-controller="home" asp-action="index">
                    Projects >>
                </a><a asp-controller="Project" asp-action="ProjectSummary">
                    @ViewBag.ProjectName >>
                </a> <a href="#">Issue Log</a>
            </h6>
            <hr />
            <div class="row">
                <div class="pill-nav" style="width:75%;margin-left:1%;">
                    <a asp-controller="Schedule" asp-action="ScheduleTable" asp-route-id="@ViewBag.ProjectCode">Schedule</a>
                    <a asp-controller="Risk" asp-action="RiskTable" asp-route-id="@ViewBag.ProjectCode">Risk Log</a>
                    <a class="active" asp-controller="Issue" asp-action="IssueTable">Issue Log</a>
                    <a asp-controller="Actiono" asp-action="ActionoTable" asp-route-id="@ViewBag.ProjectCode">Action Log</a>
                </div>
                <div>
                    <form asp-action="IssueTable" asp-controller="Issue" method="post" style="width:100%; padding:0px;">
                        <div class="row input-group">
                            <input type="text" name="search" id="search" class="form-control" placeholder="Search issue" />
                            <div>
                                <input type="submit" value="Search" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr />
            <div class="right-row">
               
                <table border="1" style="width:100%">
                    <thead style="background-color:darkorange;">
                        <tr>
                            <th>Code</th>
                            <th>Description</th>
                            <th>Owner</th>
                            <th>Impact</th>
                            <th>Status</th>
                            <th>Open Date</th>
                            <th>Close Date</th>
                            <th>Solution</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var issue in Model)
                        {
                            <tr>
                                <td>@issue.IssueCode</td>
                                <td>@issue.IssueDescription</td>
                                <td>@issue.IssueOwner</td>
                                <td>@issue.IssueImpact</td>
                                <td>@issue.IssueStatus</td>
                                <td>@issue.IssueOpenDate</td>
                                <td>@issue.IssueCloseDate</td>
                                <td>@issue.IssueAgreedSolution</td>
                                <td>
                                    <a asp-controller="Issue" asp-action="EditProjectIssue" asp-route-id="@issue.IssueCode">
                                        <i class="fa fa-marker"></i>
                                    </a>
                                    <a asp-controller="Issue" asp-action="DeleteProjectIssue" style="margin-left:15px;"
                                       asp-route-id="@issue.IssueCode" class="text-danger"
                                       onclick="return confirm('Are you sure to delete this issue?')">
                                        <i class="fa fa-trash"></i>
                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <hr />

            <div class="row" style="margin-top:80px;">
                <div style="width:50%;">
                    <a asp-controller="Issue" asp-action="ExportIssue">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:15%;">
                            Download <i class="fa fa-file-download"></i>
                        </button>
                    </a>
                </div>
                <div style="width:50%;">
                    <a asp-controller="Issue" asp-action="AddIssue">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:50%;">
                            Add Issue <i class="fa fa-plus"></i>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div><!-- end div .row-->

</body>