Models/Actiono.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_CORE_MVC_EMP_MGMT.Models
{
    public class Actiono
    {
        [Key]
        public int ActionoCode { get; set; }

        [Required]
        [Display(Name = "Action Description: ")]
        public String ActionoDescription { get; set; }

        [Required]
        [Display(Name="Action Owner")]
        public String ActionoOwner { get; set; }

        [Required]
        [Display(Name ="Responsible")]
        public String ActionoResponsible { get; set; }

        [Required]
        [Display(Name ="Deadline")]
        [DataType(DataType.Date)]
        public DateTime ActionoDeadline { get; set; }

        [Required]
        [Display(Name ="Status")]
        public ClosedOpened ActionnoStatus { get; set; }

        [Required]
        [Display(Name = "Last Update")]
        [DataType(DataType.Date)]
        public DateTime ActionoLastUpdate { get; set; }

        //foreign key
        public int? ProjectProjectCode { get; set; }
        [ForeignKey("ProjectProjectCode")]
        public virtual Project Project { get; set; }

    }
}

Controllers/ActionoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ASP.NET_CORE_MVC_EMP_MGMT.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace ASP.NET_CORE_MVC_EMP_MGMT.Controllers
{
    public class ActionoController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IActionoRepository _iActionoRepository;
        private static int code;//store  ProjectCode passed from ProjectSummary.cshtml
        private static string ProjectName;

        public ActionoController(AppDbContext context, IActionoRepository iActionoRepository)
        {
            _context = context;
            _iActionoRepository = iActionoRepository;
        }

        //when we want to edit an issue this method respond to get method to display a form which has predefined values
        //from the database the specific issue we are editing
        [HttpGet]
        public ViewResult EditProjectActiono(int Id)//Id is the IssueCode
        {
            Actiono actiono = _iActionoRepository.GetActiono(Id);
            EditUpdateActiono editUpdateActiono = new EditUpdateActiono
            {
                Id = actiono.ActionoCode,
                ActionoDescription = actiono.ActionoDescription,
                ActionoOwner = actiono.ActionoOwner,
                ActionoResponsible = actiono.ActionoResponsible,
                ActionoDeadline = actiono.ActionoDeadline,
                ActionnoStatus = actiono.ActionnoStatus,
                ActionoLastUpdate = actiono.ActionoLastUpdate,
                ActionoCode = actiono.ActionoCode
            };
            ViewBag.ProjectCode = code;
            return View(editUpdateActiono);
        }
        //EditProjectIssue(); is used to add new Issue to Issue Table so this method Post the form data to database
        [HttpPost]
        public IActionResult EditProjectActiono(EditUpdateActiono model)
        {
            if (ModelState.IsValid)
            {

                Actiono actiono = _iActionoRepository.GetActiono(model.Id);
                actiono.ActionoDescription = model.ActionoDescription;
                actiono.ActionoOwner = model.ActionoOwner;
                actiono.ActionoResponsible = model.ActionoResponsible;
                actiono.ActionoDeadline = model.ActionoDeadline;
                actiono.ActionnoStatus = model.ActionnoStatus;
                actiono.ActionoLastUpdate = model.ActionoLastUpdate;

                _iActionoRepository.Update(actiono);//Update method is found in IIssueRepository.cs
                //return RedirectToAction("ActionoTable");
                return RedirectToAction("ActionoTable", new { id = code });
            }
            return View();
        }


        //method to delete a project Issue no view is required to delete an issue so this method work on get method
        public async Task<IActionResult> DeleteProjectActiono(int id)
        {
            var actiono = await _context.Actionos.FindAsync(id);
            _context.Actionos.Remove(actiono);
            await _context.SaveChangesAsync();
            //return RedirectToAction("ActionoTable");
            return RedirectToAction("ActionoTable", new { id = code });
        }

        //method to display all Actiions of a project in table format
        public IActionResult ActionoTable(int id)
        {
            var Username = HttpContext.Session.GetString("Username");

            if (Username != null)
            {
                code = id;
                ViewBag.Code = code;
                var model = _iActionoRepository.GetAllProjectActiono(id);//interface in IIssueRepository
                ViewBag.Issue = model;
                //get the name of the project based on the id and pass it to RiskTable.cshtml to use it
                //to indicate where the user is at
                ProjectName = _context
                .Projects
                .Where(u => u.ProjectCode == id)
                .Select(u => u.projectName)
                .SingleOrDefault();
                ViewBag.ProjectName = ProjectName;

                //pass the global code value to IssueTable.cshtml
                ViewBag.ProjectCode = code;

                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }

        }
        //method to search project
        [HttpPost]
        public IActionResult ActionoTable(int id,string search = null)
        {
            id = code;
            if (!string.IsNullOrEmpty(search))//if user just press the search button without providing name to be searched
            {
                var foundActions = _iActionoRepository.SearchAction(search);
                return View(foundActions);
            }
            var allAction = _iActionoRepository.GetAllProjectActiono(id);//interface in IProjectRepository
            ViewBag.Project = allAction;

            ////get the name of the project based on the id and pass it to RiskTable.cshtml to use it
            ////to indicate where the user is at
            ProjectName = _context
            .Projects
            .Where(u => u.ProjectCode == id)
            .Select(u => u.projectName)
            .SingleOrDefault();
            ViewBag.ProjectName = ProjectName;

            //pass the global code value to IssueTable.cshtml
            ViewBag.ProjectCode = code;
            return View(allAction);

            //code = id;
            //ViewBag.Code = code;
            //var model = _iActionoRepository.GetAllProjectActiono(id);//interface in IIssueRepository
            //ViewBag.Issue = model;
            ////get the name of the project based on the id and pass it to RiskTable.cshtml to use it
            ////to indicate where the user is at
            //ProjectName = _context
            //.Projects
            //.Where(u => u.ProjectCode == id)
            //.Select(u => u.projectName)
            //.SingleOrDefault();
            //ViewBag.ProjectName = ProjectName;

            ////pass the global code value to IssueTable.cshtml
            //ViewBag.ProjectCode = code;

            //return View(model);
        }
        //AddIssue(); is used to add new Issue to Issue Table
        [HttpGet]
        public IActionResult AddActiono()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddActiono(Actiono actiono)
        {
            if (ModelState.IsValid)
            {

                Actiono act = new Actiono();
                act.ActionoDescription = actiono.ActionoDescription;
                act.ActionoOwner = actiono.ActionoOwner;
                act.ActionoResponsible = actiono.ActionoResponsible;
                act.ActionoDeadline = actiono.ActionoDeadline;
                act.ActionnoStatus = actiono.ActionnoStatus;
                act.ActionoLastUpdate = actiono.ActionoLastUpdate;
                act.ProjectProjectCode = code;

                _context.Actionos.Add(act);
                await _context.SaveChangesAsync();
                return RedirectToAction("ActionoTable", new { id = code });
            }
            return View(actiono);
        }
        // Export ActionTable to file system
        public IActionResult ExportAction()
        {
            var data = _context.Actionos.Where(ri => ri.ProjectProjectCode == code).ToList();

            var stream = new MemoryStream();
            using (var package = new ExcelPackage(stream))
            {
                var sheet = package.Workbook.Worksheets.Add("Action Log");

                sheet.Cells.LoadFromCollection(data, true);
                package.Save();
            }
            stream.Position = 0;
            var fileName = ProjectName + $" Action Log_{DateTime.Now.ToString("yyyy/MM/dd/HH:mm:ss")}.xlsx";
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);

        }

        //public IActionResult ExportAction()
        //{
        //    var data = _context.Actionos.Where(ri => ri.ProjectProjectCode == code).ToList();

        //    var stream = new MemoryStream();
        //    using (var package = new ExcelPackage(stream))
        //    {
        //        var sheet = package.Workbook.Worksheets.Add("Action Log");
        //        var rowCount = sheet.Dimension.Rows;
        //        for (int row = 2; row <= rowCount; row++)
        //        {

        //            list.Add(new Actiono
        //            {
        //                //ActionoCode = int.Parse(worksheet.Cells[row, 1].Value.ToString().Trim()),
        //                ActionoDescription = worksheet.Cells[row, 1].Value.ToString().Trim(),
        //                ActionoOwner = worksheet.Cells[row, 2].Value.ToString().Trim(),
        //                ActionoResponsible = worksheet.Cells[row, 3].Value.ToString().Trim(),
        //                ActionoDeadline = DateTime.Parse(worksheet.Cells[row, 4].Value.ToString().Trim()),
        //                ActionnoStatus = worksheet.Cells[row, 5].Value.ToString().Trim(),
        //                ActionoLastUpdate = DateTime.Parse(worksheet.Cells[row, 6].Value.ToString().Trim()),
        //                ProjectProjectCode = code,

        //            });
        //        }



        //        sheet.Cells.LoadFromCollection(data, true);
        //        package.Save();
        //    }
        //    stream.Position = 0;
        //    var fileName = ProjectName + $" Action Log_{DateTime.Now.ToString("yyyy/MM/dd/HH:mm:ss")}.xlsx";
        //    return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);

        //}


        public async Task<DemoResponse<List<Actiono>>>Import(IFormFile formFile, CancellationToken cancellationToken)
        {

Views/Actiono/ActionoTable.cshtml
<!--SHOW RISK IN THE FORM OF TABLE FOR SPECIFIC PROJECT-->
@model IEnumerable<ASP.NET_CORE_MVC_EMP_MGMT.Models.Actiono>
<head>
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    
    <!-- create two column of the page-->
    <div class="row">
        <div class="left-page" style="margin-top:60px;">
            <h3 style="font-family:Helvetica, Arial, sans-serif ;color:white; text-align:center;">Menu</h3>
            <hr style="border-width: 6px;color:white;" />
            <div>
                <a asp-controller="Home" asp-action="Index">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-home" style="padding-right:12px;"></i>
                        Home
                    </button>
                </a>
            </div>
            @*<button type="button" class="collapsible" style="font-size:17px;">
                <i class="fa fa-folder" style="padding-right:12px;"></i>Projects  <i class="fas fa-angle-right"></i>
            </button>*@
            <div>
                <a asp-controller="Project" asp-action="CreateNewProject">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fas fa-folder-plus" style="padding-right:12px;"></i>Create Project
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Project" asp-action="ProjectSummary">
                    <button type="button" class="collapsible" style="font-size:17px;">
                        <i class="fa fa-file-signature" style="padding-right:12px;">  </i>Project Summary
                    </button>
                </a>
            </div>
            <div>
                <a asp-controller="Risk" asp-action="GenerateReport">
                    <button type="button" class="collapsible btn btn-primary" style="font-size:17px;">
                        <i class="fa fa-file-download" style="padding-right:12px;">  </i>  Generate Report
                    </button>
                </a>

            </div>
        </div><!--end left page-->
        <div class="right-page" style="background-color:white;">
            <h6 style="margin-left:60%;">
                You are at: <a asp-controller="home" asp-action="index">
                    Projects >>
                </a><a asp-controller="Project" asp-action="ProjectSummary">
                    @ViewBag.ProjectName >>
                </a> <a href="#">Action Log</a>
            </h6>
            <hr />
            <div class="row">
                <div class="pill-nav" style="width:75%;margin-left:1%;">
                    <a asp-controller="Schedule" asp-action="ScheduleTable" asp-route-id="@ViewBag.ProjectCode">Schedule</a>
                    <a asp-controller="Risk" asp-action="RiskTable" asp-route-id="@ViewBag.ProjectCode">Risk Log</a>
                    <a asp-controller="Issue" asp-action="IssueTable" asp-route-id="@ViewBag.ProjectCode">Issue Log</a>
                    <a class="active" asp-controller="Actiono" asp-action="ActionoTable">Action Log</a>
                    
                </div>
                <div>
                    <form asp-action="ActionoTable" asp-controller="Actiono" method="post" style="width:100%; padding:0px;">
                        <div class="row input-group">
                            <input type="text" name="search" id="search" class="form-control" placeholder="Search action" />
                            <div>
                                <input type="submit" value="Search" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr />
            <div class="right-row">
                <table border="1" style="width:100%">
                    <thead style="background-color:darkorange;">
                        <tr>
                            <th>Code</th>
                            <th>Description</th>
                            <th>Owner</th>
                            <th>Responsible</th>
                            <th>Deadline</th>
                            <th>Status</th>
                            <th>Last Update</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var actiono in Model)
                        {
                            <tr>
                                <td>@actiono.ActionoCode</td>
                                <td>@actiono.ActionoDescription</td>
                                <td>@actiono.ActionoOwner</td>
                                <td>@actiono.ActionoResponsible</td>
                                <td>@actiono.ActionoDeadline</td>
                                <td>@actiono.ActionnoStatus</td>
                                <td>@actiono.ActionoLastUpdate</td>
                                <td>
                                    <a asp-controller="Actiono" asp-action="EditProjectActiono" asp-route-id="@actiono.ActionoCode">
                                        <i class="fa fa-marker"></i>
                                    </a>
                                    <a asp-controller="Actiono" asp-action="DeleteProjectActiono" style="margin-left:15px;"
                                       asp-route-id="@actiono.ActionoCode" class="text-danger"
                                       onclick="return confirm('Are you sure to delete this Action?')">
                                        <i class="fa fa-trash"></i>
                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <hr />


            <div class="row" style="margin-top:80px;">
                <div style="width:35%;">
                    <a asp-controller="Actiono" asp-action="ExportAction">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:15%;">
                            Download <i class="fa fa-file-download"></i>
                        </button>
                    </a>
                </div>

                <div style="width:30%;">
                    @using (Html.BeginForm("Import", "Actiono", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        @Html.Raw(ViewBag.Error)
                        <input type="file" name="formFile" class="btn btn-outline-primary" />
                    <br />
                        <br/>
                        
                        <button class="btn btn-outline-primary" type="submit" style="width:200px; margin-left:20%;">
                            Import Excel <i class="fa fa-file-import"></i>
                        </button>
                    }
                </div>
                

                
                @*<div style="width:33%;">
                    <a asp-controller="Actiono" asp-action="Import">
                        <button class="btn btn-outline-primary" type="submit" style="width:200px; margin-left:50%;">
                            Import Excel <i class="fa fa-file-import"></i>
                        </button>
                    </a>
                </div>*@
               

                <div style="width:20%;">
                    <a asp-controller="Actiono" asp-action="AddActiono">
                        <button class="btn btn-outline-primary" style="width:200px; margin-left:50%;">
                            Add Action <i class="fa fa-plus"></i>
                        </button>
                    </a>
                </div>

            </div>
        </div>
    </div><!-- end div .row-->

</body>

Views/Actiono/AddActiono.cshtml
@model Actiono
@{
    ViewData["Title"] = "Adding Project Action";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%; margin-top:80px;">
        <form asp-controller="ActionoController" asp-action="AddActiono" method="post">
            <br />
            <h3 style="color:#003cff;">Adding Project Action</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="ActionoDescription"></label>
                    <input asp-for="ActionoDescription" class="form-control" />
                    <span asp-validation-for="ActionoDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoOwner"></label>
                    <input asp-for="ActionoOwner" class="form-control" />
                    <span asp-validation-for="ActionoOwner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoResponsible"></label>
                    <input asp-for="ActionoResponsible" class="form-control" />
                    <span asp-validation-for="ActionoResponsible" class="text-danger"></span>
                </div>
                <div style="width:50%; margin-top:40px;">
                    <button class="btn btn-danger btn-block" asp-controller="Actiono"
                            asp-action="ActionoTable" asp-route-id="@ViewBag.ProjectCode">Cancel </button>
                </div>

            </div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                @*<div class="form-group">
                    <label asp-for="ActionnoStatus"></label>
                    <input asp-for="ActionnoStatus" class="form-control" />
                    <span asp-validation-for="ActionnoStatus" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="ActionnoStatus"></label>
                    <div>
                        <select asp-for="ActionnoStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="ActionnoStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoDeadline"></label>
                    <input asp-for="ActionoDeadline" class="form-control" />
                    <span asp-validation-for="ActionoDeadline" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ActionoLastUpdate"></label>
                    <input asp-for="ActionoLastUpdate" class="form-control" />
                    <span asp-validation-for="ActionoLastUpdate" class="text-danger"></span>
                </div>
                <div style="margin-left:50%; width:50%; margin-top:40px;">
                    <input type="submit" class="btn btn-primary btn-block" value="Add Action" />
                </div>
            </div>
        </form>
    </div>

</div>

Views/Actiono/EditProjectActiono.cshtml
@model EditUpdateActiono
@{
    ViewData["Title"] = "Editing Project Action";
}
<head>
    <link rel="stylesheet" href="~/css/AddProjectRisk.css" />
</head>
<div class="row" style="background-color:white; margin-left:10%; width:80%;">
    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded" style="margin-left:8%; margin-top:80px;">
        <form asp-controller="Actiono" asp-action="EditProjectActiono" method="post">
            <!--this input field store the id of the risk which we are updating-->
            <input hidden asp-for="ActionoCode" />
            
            <h3 style="color:#003cff;">Editing Project Action</h3>
            <hr />
            <div class="text-success">@ViewBag.Success</div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="ActionoDescription"></label>
                    <input asp-for="ActionoDescription" class="form-control" />
                    <span asp-validation-for="ActionoDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoOwner"></label>
                    <input asp-for="ActionoOwner" class="form-control" />
                    <span asp-validation-for="ActionoOwner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoResponsible"></label>
                    <input asp-for="ActionoResponsible" class="form-control" />
                    <span asp-validation-for="ActionoResponsible" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ActionoDeadline"></label>
                    <input asp-for="ActionoDeadline" class="form-control" />
                    <span asp-validation-for="ActionoDeadline" class="text-danger"></span>
                </div>



            </div>
            <div class="leftright" style="padding-left:5%;padding-right:5%;">
                <div class="form-group">
                    <label asp-for="ActionoDeadline"></label>
                    <input asp-for="ActionoDeadline" class="form-control" />
                    <span asp-validation-for="ActionoDeadline" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="ActionnoStatus"></label>
                    <input asp-for="ActionnoStatus" class="form-control" />
                    <span asp-validation-for="ActionnoStatus" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="ActionnoStatus"></label>
                    <div>
                        <select asp-for="ActionnoStatus" class="custom-select mr-sm-2"
                                asp-items="Html.GetEnumSelectList<ClosedOpened>()">
                            <option value="">Please select</option>
                        </select>
                    </div>
                    <span asp-validation-for="ActionnoStatus" class="text-danger"></span>
                </div>
                <div class="form-group" style="padding-bottom:8%;">
                    <label asp-for="ActionoLastUpdate"></label>
                    <input asp-for="ActionoLastUpdate" class="form-control" />
                    <span asp-validation-for="ActionoLastUpdate" class="text-danger"> </span>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-spinner fa-spin"></i> Update</button>
                    </div>
                    <div class="form-group col-md-6">
                        <a asp-controller="Actiono" asp-action="ActionoTable" asp-route-id="@ViewBag.ProjectCode" class="btn btn-secondary btn-block"><i class=" fa fa-table"></i> Back To Table</a>
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>

Views/Actiono/index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Choose excel file to upload</title>
</head>
<body>
    @using (Html.BeginForm("Import", "Actiono", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.Raw(ViewBag.Error)
        <span>MPP or Excel File </span><input type="file" name="formFile" />
        <br />
        <input type="submit" value="Import" />
    }
</body>
</html>